### ISSUE TITLE
ScrollView is not scrollable

### ISSUE THREAD

**Issue by ansarikhurshid786** [tsepeti/react-native-bdrawer#2]
It is really very nice component which look native. but I am facing issue. it is not scrollable. 

anyone has same issue

**Comment by yasaricli** [comment]
hello @ansarikhurshid786 

When we developed this component, there was no **react-native-raw-bottom-sheet** package. I think you can use **react-native-raw-bottom-sheet** now.

https://github.com/nysamnang/react-native-raw-bottom-sheet
